# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-19 13:59
# Copyright (C) 2016-2020 TU Muenchen and contributors of ANEXIA Internetdienstleistungs GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later
#
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0096_booking_rules_adjustments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebooking',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='resourcebooking',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='resourcebooking',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='resourcebooking',
            name='resource',
        ),
        migrations.DeleteModel(
            name='ResourceBooking',
        ),
    ]
