# Generated by Django 2.2.17 on 2020-11-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0101_user_ordering'),
        ('resources', '0001_add_study_room_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='branch_library',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='study_room',
        ),
    ]
