# Generated by Django 2.2.17 on 2021-02-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0102_extract_study_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebookingrulebookablehours',
            name='full_day',
            field=models.BooleanField(db_index=True, default=True, verbose_name='full day'),
        ),
    ]
