# Generated by Django 2.2.27 on 2022-02-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0108_resourcebookingrulebookablehours_different_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcebookingrulebookablehours',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='resourcebookingrulebookablehours',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='resourcebookingrulebookablehours',
            name='wednesday',
        ),
        migrations.RemoveField(
            model_name='resourcebookingrulebookablehours',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='resourcebookingrulebookablehours',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='resourcebookingrulebookablehours',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='resourcebookingrulebookablehours',
            name='sunday',
        ),
    ]
