# Generated by Django 2.2.24 on 2022-03-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0109_resourcebookingrulebookablehours_remove_weekday_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementlock',
            name='webdav_lock',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Whether this lock was set while using webdav'),
        ),
    ]
