# Generated by Django 2.2.27 on 2022-03-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0111_refactor_choices_general_usage_setting'),
        ('projects', '0110_elementlock_webdav_lock'),
    ]

    operations = [
    ]
