# Generated by Django 2.2.28 on 2022-04-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0113_refactor_resource_general_usage_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='general_usage_setting',
            field=models.CharField(blank=True, choices=[('1', 'Only selected user groups'), ('2', 'Global')], default=None, max_length=3, null=True, verbose_name='General usage setting for this resource'),
        ),
    ]
