# Generated by Django 2.2.12 on 2020-05-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_fix_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulednotification',
            name='timedelta_unit',
            field=models.CharField(choices=[('MINUTE', 'minutes'), ('HOUR', 'hours'), ('DAY', 'days'), ('WEEK', 'weeks')], max_length=6, verbose_name='Time unit when the notification should be created'),
        ),
        migrations.AlterField(
            model_name='schedulednotification',
            name='timedelta_value',
            field=models.IntegerField(verbose_name='Time value when the notification should created'),
        ),
    ]
