---
- name: Copy daphne.service
  template:
    src: daphne.service.j2
    dest: /etc/systemd/system/daphne.service
    owner: root
    group: root
    mode: '0644'
    force: yes
  become: yes

- name: Copy daphne.socket
  copy:
    src: daphne.socket
    dest: /etc/systemd/system/daphne.socket
    owner: root
    group: root
    mode: '0644'
    force: yes
  become: yes

- name: Copy daphne_restart.service
  copy:
    src: daphne_restart.service
    dest: /etc/systemd/system/daphne_restart.service
    owner: root
    group: root
    mode: '0644'
    force: yes
  become: yes

- name: Copy daphne_restart.path
  copy:
    src: daphne_restart.path
    dest: /etc/systemd/system/daphne_restart.path
    owner: root
    group: root
    mode: '0644'
    force: yes
  become: yes

- name: Copy daphne.conf
  template:
    src: daphne.conf.j2
    dest: /etc/tmpfiles.d/daphne.conf
    owner: root
    group: root
    mode: '0644'
    force: yes
  become: yes

- name: Enable service daphne_restart.path
  systemd:
    name: daphne_restart.path
    state: started
    enabled: true
  become: yes

- name: Enable service daphne.socket
  systemd:
    name: daphne.socket
    state: started
    enabled: true
  become: yes
