version: '3'
volumes:
  pg_data:
  maildump_data:
  app_data:
services:
  # python container
  python: &python
    build:
      context: . # We set this context to load the app requirements when building the image
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./:/app
      - app_data:/var/lib/app
      - ./dss:/dss
    # command: python -Wd manage.py runserver 0.0.0.0:8000
    command: gunicorn --workers 4 --bind 0.0.0.0:8000 eric.asgi:application -k uvicorn.workers.UvicornWorker
    environment:
      - DJANGO_SETTINGS_MODULE=eric.settings.docker
      - PYTHONUNBUFFERED=1
      - PACKAGE_VERSION=0.3.1  # Remove this after upgrading to the official release of django-userforeignkey
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
      - maildump
      - redis
      - ldap-service
  cron_remove_old_element_locks:
    <<: *python
    ports: []
    volumes:
      - ./:/app
      - app_data:/var/lib/app
    command: while true; do python manage.py remove_old_element_locks; sleep 10; done
  cron_send_notifications:
    <<: *python
    ports: []
    volumes:
      - ./:/app
      - app_data:/var/lib/app
    command: while true; do python manage.py send_notifications; sleep 60; done
  cron_trash_unneeded_tmp_files:
    <<: *python
    ports: []
    volumes:
      - ./:/app
      - app_data:/var/lib/app
    command: while true; do python manage.py trash_unneeded_tmp_files; sleep 60; done
#  # Celery
#  celery:
#    <<: *python
#    ports: []
#    volumes:
#      - ./:/app
#      - app_data:/var/lib/app
#      - ./dss:/dss
#    command: celery -A eric worker -B -l INFO
#    environment:
#      - DJANGO_SETTINGS_MODULE=eric.settings.docker
#    depends_on:
#      - broker
#      - python
#  # RabbitMQ Broker used by celery
#  broker:
#    image: rabbitmq:3.8
#    hostname: broker
#    environment:
#      - RABBITMQ_DEFAULT_USER=admin
#      - RABBITMQ_DEFAULT_PASS=mypass
#    ports:
#      - 5672:5672
  # Postgres configuration
  db:
    image: postgres:12.3
    command: postgres -c jit=off
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./backups:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: eric
      POSTGRES_USER: eric
      POSTGRES_PASSWORD: eric
  adminer:
    image: adminer
    ports:
      - 1082:8080
  # Maildump configuration
  maildump:
    build:
      context: ./docker/maildump
      args:
        MAILDUMP_VERSION: 1.0
    volumes:
      - maildump_data:/maildump
    expose:
      - 1025
      - 1080
    ports:
      - 1080:1080
      - 1025:1025
  redis:
    image: redis:5.0
    expose:
      - 6379
    ports:
      - 6379:6379
  # ldap server
  ldap-service:
    command: "--loglevel trace"
    image: osixia/openldap:1.5.0
    ports:
     - 389:389
     - 636:636
    environment:
     - LDAP_ORGANISATION=Workbench Local Dev
     - LDAP_DOMAIN=0.0.0.0
    command: "--copy-service"
    volumes:
     - ./ldap/:/ldap
     - ./data/docker_ldap_data:/var/lib/ldap
     - ./data/docker_ldap_config:/etc/ldap/slapd.d
  # ldap admin
  ldap-admin:
    image: dinkel/phpldapadmin:latest
    ports:
     - 1081:80
    environment:
     - LDAP_SERVER_HOST=ldap-service
    depends_on:
     - ldap-service
