[tool.isort]
known_first_party = ["eric"]
known_django = ["django"]
known_djangorestframework = ["rest_framework"]
sections = ["FUTURE", "STDLIB", "DJANGO", "DJANGORESTFRAMEWORK", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
profile = "black"
multi_line_output = 3
line_length = 120
skip = "**migrations**"
skip_gitignore = true

[tool.black]
line_length = 120
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    manage.py
  | migrations
)/
'''
