#
# Copyright (C) 2016-2020 TU Muenchen and contributors of ANEXIA Internetdienstleistungs GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Generated by Django 2.2.12 on 2020-05-08 09:29
import json

from django.db import migrations, transaction
from django.db.migrations import RunPython


@transaction.atomic
def update_groups(apps, schema_editor):
    fixture_group = load_groups_fixture()[0]
    update_group(apps, fixture_group)


def update_group(apps, fixture_group):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    db_group, created = Group.objects.get_or_create(name=fixture_group['name'])

    permission_list = Permission.objects.filter(codename__in=fixture_group['permissions'])
    db_group.permissions.set(permission_list)


def load_groups_fixture():
    return json.loads('''[
        {
          "name": "DSS Curator",
          "permissions": [
            "add_dsscontainer",
            "change_dsscontainer",
            "delete_dsscontainer",
            "view_dsscontainer",
            "trash_dsscontainer",
            "restore_dsscontainer",
            "change_project_dsscontainer",
            "add_dsscontainer_without_project"
          ]
        }
    ]''')


class Migration(migrations.Migration):
    dependencies = [
        ('dss', '0001_initial'),
    ]

    operations = [
        RunPython(
            update_groups,
            RunPython.noop  # no undo possible
        )
    ]
