# Generated by Django 3.2.8 on 2021-11-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0005_data_migrate_idtags_out_of_existing_dir_metadata_jsons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dssenvelope',
            name='metadata_file_content',
            field=models.JSONField(blank=True, verbose_name='The JSON content of the metadata file within this envelope'),
        ),
    ]
