# Generated by Django 2.2.9 on 2019-12-19 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texttemplates', '0003_changesets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='texttemplate',
            options={'ordering': ['name'], 'verbose_name': 'Text Template', 'verbose_name_plural': 'Text Templates'},
        ),
    ]
