# Generated by Django 2.2.12 on 2020-05-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texttemplates', '0004_migrate_view_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextTemplate',
        ),
    ]
