#!/bin/bash

# check who owns the working directory
USER_ID=$(stat -c "%u" $PWD)

if [ "$USER_ID" -eq "0" ]; then
    echo "Are you on Windows? Overriding user_id with 1000"
    USER_ID=1000
fi

echo "Directory $PWD is owned by user with id ${USER_ID}"

# set the python run uid to the user id we just retrieved
NODE_RUN_UID=${PYTHON_RUN_UID:=${USER_ID}}
NODE_RUN_USER=${NODE_RUN_USER:=user}
NODE_RUN_GROUP=${NODE_RUN_GROUP:=user}
NODE_RUN_USER_TEST=$(grep "[a-zA-Z0-9\-\_]*:[a-zA-Z]:${NODE_RUN_UID}:" /etc/passwd)

# Make sure the given group exists
getent group $NODE_RUN_GROUP > /dev/null || groupadd $NODE_RUN_GROUP > /dev/null

# Update the user to the configured UID and group if
# it already exists.
if [ -n "${NODE_RUN_USER_TEST}" ]; then
    echo "Update user '$NODE_RUN_USER'"

    usermod -l ${NODE_RUN_USER} $(id -un ${NODE_RUN_UID}) 1> /dev/null 2>&1
    usermod -u $NODE_RUN_UID -g $NODE_RUN_GROUP $NODE_RUN_USER 1> /dev/null 2>&1

# Else create the user with the configured UID and group
else
    echo "Create user '$NODE_RUN_USER'"

    # Create the user with the corresponding group
    useradd -u $NODE_RUN_UID -g $NODE_RUN_GROUP -d /home/$NODE_RUN_USER $NODE_RUN_USER 1> /dev/null 2>&1
fi

# Make sure $HOME directory of user exists
mkdir /home/$NODE_RUN_USER 1> /dev/null 2>&1
chown $NODE_RUN_USER:$NODE_RUN_GROUP /home/$NODE_RUN_USER
export HOME=/home/$NODE_RUN_USER

# Make the user a sudoer
echo "$NODE_RUN_USER ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/100-$NODE_RUN_USER
echo "Defaults:$NODE_RUN_USER !requiretty" >> /etc/sudoers

# Fix permissions of sudoers files
chmod 600 /etc/sudoers
chmod 600 /etc/sudoers.d/100-$NODE_RUN_USER

# Setup data storage for the application
mkdir -p /var/lib/app 1> /dev/null 2>&1
chown -R $NODE_RUN_USER:$NODE_RUN_GROUP /var/lib/app
find /var/lib/app -type d -exec chmod 750 {} +
find /var/lib/app -type f -exec chmod 640 {} +

# Block the container if no commands supplied
if [ $# -eq 0 ]; then
    exec sleep infinity

# Else start the supplied commands with the configured
# user.
else
    echo "Executing $@"
    exec sudo -u $NODE_RUN_USER /bin/bash -c "cd $PWD; $*"
fi
