# Generated by Django 2.2.24 on 2022-04-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_add_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatafield',
            name='base_type',
            field=models.CharField(choices=[('whole_number', 'Integer'), ('decimal_number', 'Decimal number'), ('currency', 'Currency'), ('date', 'Date'), ('real_date', 'Real Date'), ('time', 'Time'), ('percentage', 'Percentage'), ('text', 'Text'), ('fraction', 'Fraction'), ('gps', 'GPS'), ('checkbox', 'Checkbox'), ('selection', 'Selection')], max_length=32, verbose_name='Metadata base type'),
        ),
    ]
