# Generated by Django 3.2.8 on 2021-11-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_add_real_date_base_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='values',
            field=models.JSONField(verbose_name='Field values'),
        ),
        migrations.AlterField(
            model_name='metadatafield',
            name='type_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Values for base type settings'),
        ),
    ]
