# Generated by Django 2.2.12 on 2020-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_migrate_view_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='additional_information',
            field=models.TextField(blank=True, verbose_name='Additional information about the user'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Last name'),
        ),
    ]
