# Generated by Django 2.2.16 on 2020-10-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_field_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
