# Generated by Django 3.2.15 on 2022-10-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_add_affiliation_prim'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_invited',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date when this user was invited'),
        ),
    ]
