---
- name: Copy /etc/logrotate.d/celerybeat
  copy:
    src: logrotate_celerybeat
    dest: /etc/logrotate.d/celerybeat
    owner: root
    group: root
    mode: '0644'
    force: yes
  become: yes

- name: Copy celerybeat.service
  template:
    src: celerybeat.service.j2
    dest: /etc/systemd/system/celerybeat.service
    owner: root
    group: root
    mode: '0644'
    force: yes
  become: yes

- name: Enable service celerybeat
  systemd:
    name: celerybeat
    state: started
    enabled: yes
  become: yes

- name: Copy celerybeat.conf
  template:
    src: celerybeat.conf.j2
    dest: /etc/tmpfiles.d/celerybeat.conf
    owner: root
    group: root
    mode: '0644'
    force: yes
  become: yes

- name: systemd-tmpfiles --create
  command: "systemd-tmpfiles --create"
  become: yes

- name: Install rabbitmq-server
  package:
    name: rabbitmq-server
    state: present
  become: yes

- name: rabbitmqctl add_user myruser myrpassword
  command: "rabbitmqctl add_user myruser myrpassword"
  become: yes

- name: rabbitmqctl add_vhost myrvhost
  command: "rabbitmqctl add_vhost myrvhost"
  become: yes

- name: rabbitmqctl set_user_tags myruser myrtag
  command: "rabbitmqctl set_user_tags myruser myrtag"
  become: yes

- name: rabbitmqctl set_permissions -p myrvhost myruser ".*" ".*" ".*"
  command: 'rabbitmqctl set_permissions -p myrvhost myruser ".*" ".*" ".*"'
  become: yes
