# Generated by Django 2.2.14 on 2020-07-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_boards', '0014_migrate_view_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbanboard',
            name='title',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Title of the Kanban Board'),
        ),
    ]
