# Generated by Django 2.2.24 on 2021-08-11 12:55

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban_boards', '0017_adjust_column_default_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanBoardUserFilterSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Kanban Board User Filter Settings')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Date when this element was created')),
                ('last_modified_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Date when this element was last modified')),
                ('kanban_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_board_user_filter_settings', to='kanban_boards.KanbanBoard', verbose_name='Which kanban board is this user filter setting for')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Kanban Board User Filter Setting',
                'verbose_name_plural': 'Kanban Board User Filter Settings',
                'unique_together': {('kanban_board', 'user')},
                'index_together': {('kanban_board', 'user')},
            },
        ),
    ]
