# Generated by Django 2.2.20 on 2021-08-19 06:51

from django.db import migrations
import django_cleanhtmlfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_boards', '0018_kanbanboarduserfiltersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanboard',
            name='description',
            field=django_cleanhtmlfield.fields.HTMLField(blank=True, verbose_name='Description of the Kanban Board'),
        ),
    ]
