# Generated by Django 3.2.8 on 2021-11-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_boards', '0021_task_board_columns_rgba_regex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbanboarduserfiltersetting',
            name='settings',
            field=models.JSONField(blank=True, null=True, verbose_name='Kanban Board User Filter Settings'),
        ),
    ]
