---
- name: Copy gunicorn.service
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
    owner: root
    group: root
    mode: '0644'
    force: yes
  become: yes

- name: Copy gunicorn.socket
  copy:
    src: gunicorn.socket
    dest: /etc/systemd/system/gunicorn.socket
    owner: root
    group: root
    mode: '0644'
    force: yes
  become: yes

- name: Copy gunicorn_restart.service
  copy:
    src: gunicorn_restart.service
    dest: /etc/systemd/system/gunicorn_restart.service
    owner: root
    group: root
    mode: '0644'
    force: yes
  become: yes

- name: Copy gunicorn_restart.path
  copy:
    src: gunicorn_restart.path
    dest: /etc/systemd/system/gunicorn_restart.path
    owner: root
    group: root
    mode: '0644'
    force: yes
  become: yes

- name: Copy gunicorn.conf
  template:
    src: gunicorn.conf.j2
    dest: /etc/tmpfiles.d/gunicorn.conf
    owner: root
    group: root
    mode: '0644'
    force: yes
  become: yes

- name: Create tmpfiles for gunicorn
  ansible.builtin.command: sudo systemd-tmpfiles --create
  become: yes

- name: Reload daemon for gunicorn
  systemd:
    daemon_reload: true
  become: yes

- name: Enable gunicorn.service
  systemd:
    name: gunicorn.service
    state: started
    enabled: yes
  become: yes

- name: Enable gunicorn.socket
  systemd:
    name: gunicorn.socket
    state: started
    enabled: yes
  become: yes

- name: Enable service gunicorn_restart.path
  systemd:
    name: gunicorn_restart.path
    state: started
    enabled: true
  become: yes

- name: Enable service gunicorn_restart.service
  systemd:
    name: gunicorn_restart.service
    state: started
    enabled: true
  become: yes
