---
- include_vars: vars/vault.yml

- name: Install samba
  package:
    name: samba
    state: present
  become: yes

- name: Install cifs-utils
  package:
    name: cifs-utils
    state: present
  become: yes

- name: Copy NAS automount file
  copy:
    src: mnt-nas_tuze_bib_workbench.automount
    dest: /etc/systemd/system/mnt-nas_tuze_bib_workbench.automount
    owner: root
    group: root
    mode: '0644'
    force: yes
  become: yes

- name: Copy NAS mount file
  template:
    src: mnt-nas_tuze_bib_workbench.mount.j2
    dest: /etc/systemd/system/mnt-nas_tuze_bib_workbench.mount
    owner: root
    group: root
    mode: '0644'
    force: yes
  become: yes

- name: create /etc/samba/creds
  file:
    path: /etc/samba/creds
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Copy NAS automount creds
  copy:
    content: '{{ tuze_bib_workbench_nas }}'
    dest: /etc/samba/creds/tuze_bib_workbench_nas
    owner: root
    group: root
    mode: '0700'
    force: yes
  become: yes

- name: Enable service mnt-nas_tuze_bib_workbench.automount
  systemd:
    name: mnt-nas_tuze_bib_workbench.automount
    enabled: yes
  become: yes

- name: Enable service mnt-nas_tuze_bib_workbench.mount
  systemd:
    name: mnt-nas_tuze_bib_workbench.mount
    enabled: yes
  become: yes
