---
dependencies:
  - rsync
  - virtualenv
  - samba
  - cifs-utils
  - git
  - build-essential
  - python-dev
  - python3-dev
  - libsasl2-dev
  - libldap2-dev
  - libssl-dev
  - gettext
  - python3-pip
  - python3-setuptools
  - python3-wheel
  - python3-cffi
  - libcairo2
  - libpango-1.0-0
  - libpangocairo-1.0-0
  - libgdk-pixbuf2.0-0
  - libffi-dev
  - shared-mime-info
  - curl
