# Generated by Django 2.2.9 on 2019-12-19 10:28

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('caldav', '0002_add_created_by_at_last_modified_by_at_mixin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caldavitem',
            name='deleted_via_caldav_by',
            field=django_userforeignkey.models.fields.UserForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='The user that deleted the item via CalDav'),
        ),
    ]
