version: '2'
services:
  # Node configuration
  node:
    build:
      context: ./docker/node
    volumes:
      - ./:/app
    command: npm install && gulp run-server
    ports:
      - "8080:8080"
    expose:
      - "8080"
