# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-14 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_elements', '0019_tasks_alter_related_name_of_labels_to_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchecklist',
            name='title',
            field=models.CharField(max_length=2000, verbose_name='Title of the checklist item'),
        ),
    ]
