# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-17 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_elements', '0020_increase_task_checklist_text_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskchecklist',
            options={'ordering': ['task__task_id', 'created_at'], 'verbose_name': 'Task Checklist Item', 'verbose_name_plural': 'Task Checklist Items'},
        ),
    ]
