# Generated by Django 2.2.12 on 2020-05-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_elements', '0026_create_calendaraccess_for_each_user_and_give_full_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassigneduser',
            name='assigned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.MyUser', verbose_name='Which user is the task assigned to'),
        ),
        migrations.AlterField(
            model_name='taskassigneduser',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared_elements.Task', verbose_name='Which task is the user assigned to'),
        ),
        migrations.AlterField(
            model_name='taskchecklist',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='shared_elements.Task', verbose_name='Which task this checklist item belongs to'),
        ),
    ]
