# Generated by Django 2.2.16 on 2020-09-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_elements', '0029_alter_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='imported',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Whether this entry was imported by a dss import task or not'),
        ),
    ]
