# Generated by Django 2.2.17 on 2021-01-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_elements', '0031_elementlabel_new_regex_validator_patter_for_color_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='full_day',
            field=models.BooleanField(db_index=True, default=False, verbose_name='full day'),
        ),
        migrations.AddField(
            model_name='task',
            name='full_day',
            field=models.BooleanField(db_index=True, default=False, verbose_name='full day'),
        ),
    ]
