# Generated by Django 2.2.20 on 2021-09-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_elements', '0035_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.TextField(db_index=True, verbose_name='Subject of the note'),
        ),
    ]
