# Generated by Django 2.2.24 on 2021-09-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_elements', '0037_task_title_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remind_assignees',
            field=models.BooleanField(db_index=True, default=False, verbose_name='remind assignees'),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Task reminder datetime'),
        ),
    ]
