# Generated by Django 2.2.28 on 2022-05-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_elements', '0042_revert_migrate_numeric_task_priority_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('5', 'Very High'), ('4', 'High'), ('3', 'Normal'), ('2', 'Low'), ('1', 'Very Low')], default='3', max_length=5, verbose_name='Priority of the task'),
        ),
    ]
