# Generated by Django 3.2.8 on 2021-11-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0003_metadata-no-default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='metadata',
            field=models.JSONField(blank=True, verbose_name='Meta data for this version of the related entity'),
        ),
    ]
