#
# Copyright (C) 2016-present TU Muenchen and contributors of ANEXIA Internetdienstleistungs GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later
#
from django.conf import settings

cfg = settings.DSS_SETTINGS
DSS_MOUNT_PATH = cfg.get("MOUNT_PATH")
METADATA_FILE_NAME = cfg.get("METADATA_FILE_NAME")
ERROR_EMAIL_RECEIVER_CLIENT = cfg.get("ERROR_EMAIL_RECEIVER_CLIENT")
ERROR_EMAIL_RECEIVER_INTERNAL = cfg.get("ERROR_EMAIL_RECEIVER_INTERNAL")
CHECK_GLOBUS_RABBITMQ_QUEUE = cfg.get("CHECK_GLOBUS_RABBITMQ_QUEUE")
GLOBUS_RABBITMQ_HOST = cfg.get("GLOBUS_RABBITMQ_HOST")
GLOBUS_RABBITMQ_PORT = cfg.get("GLOBUS_RABBITMQ_PORT")
GLOBUS_RABBITMQ_VIRTUAL_HOST = cfg.get("GLOBUS_RABBITMQ_VIRTUAL_HOST")
GLOBUS_RABBITMQ_QUEUE = cfg.get("GLOBUS_RABBITMQ_QUEUE")
GLOBUS_RABBITMQ_USER = cfg.get("GLOBUS_RABBITMQ_USER")
GLOBUS_RABBITMQ_PASSWORD = cfg.get("GLOBUS_RABBITMQ_PASSWORD")
GLOBUS_RABBITMQ_SSL_CA_CERT = cfg.get("GLOBUS_RABBITMQ_SSL_CA_CERT")
GLOBUS_RABBITMQ_MESSAGE_FETCH_SIZE = cfg.get("GLOBUS_RABBITMQ_MESSAGE_FETCH_SIZE")
